[id]
  contentDir = "content/id"
  disabled = false
  languageCode = 'id-ID'
  languageDirection = 'ltr'
  languageName = 'Indonesia'
  title = 'WebBarengReza'
  weight = 10
  [id.params]
    footer = 'Website ini diurus oleh <a class="text-muted hover-custom-1" href="/contributors/reza-hidayat-m/"><u>Reza Hidayat M</u></a>.'

[en]
  contentDir = "content/en"
  disabled = false
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  title = 'Project Documentation'
  weight = 15
  [en.params]
    footer = 'Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a>'
