title: Menjelajah Bareng Reza
logo: /assets/img/logo.png
description: Web ini berisi setiap hal menarik yang saya temukan untuk dibagikan kepada pembaca.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
